parser: babel-eslint
plugins:
  - prettier
  - known-imports
  - ad-hok
  - styles-object
extends:
  - prettier
  - react-app
  - plugin:known-imports/recommended-react
  - plugin:ad-hok/recommended
rules:
  prettier/prettier: error
  ad-hok/require-adddisplayname: error
  styles-object/no-unused-styles: error
  styles-object/no-undef-styles: error
settings:
  ad-hok/should-fix-flow-flowmax: true
